exports.PAYMENTS_METHS = {
    'Accord D': 'mp01',
    'American Express': 'mp02',
    'C.O.D': 'mp03',
    'Cash': 'mp04',
    'Certified Cheque': 'mp05',
    'Cheque': 'mp06',
    'Gift Certificate': 'mp07',
    'Interac': 'mp08',
    'Debit Card': 'mp08',
    'MasterCard': 'mp09',
    'Money Order': 'mp10',
    'PayPal': 'mp11',
    'Visa': 'mp12',
    'Email Transfer': 'mp13',
    'Discover': 'mp14',
    'Dinners Club': 'mp15',
    'Wire Transfer': 'mp16',
    "Traveler's Cheque": 'mp17',
    'eCheck': 'mp18',
    'Direct Debit': 'mp19',
    'Personal Account': 'mp20',
    'Not applicable': 'mp21',
    'Square': 'mp22'
}

exports.LANGUAGES = {
    'Arabic': 'lang04',
    'Belarusian': 'lang08',
    'Bulgarian': 'lang12',
    'Cantonese': 'lang13',
    'Croatian': 'lang19',
    'Czech': 'lang20',
    'Danish': 'lang21',
    'Dutch': 'lang23',
    'English': 'lang25',
    'Finnish': 'lang27',
    'French': 'lang29',
    'German': 'lang32',
    'Greek': 'lang34',
    'Haitian Creole': 'lang39',
    'Hindi': 'lang42',
    'Hungarian': 'lang43',
    'Inuktitut': 'lang48',
    'Inuvialuktun': 'lang49',
    'Italian': 'lang50',
    'Japanese': 'lang51',
    'Khmer': 'lang55',
    'Korean': 'lang59',
    'Mandarin': 'lang71',
    'Persian': 'lang82',
    'Polish': 'lang83',
    'Portuguese': 'lang84',
    'Russian': 'lang88',
    'Spanish': 'lang98',
    'Tagalog ': 'lang101',
    'Taiwanese': 'lang102',
    'Thai': 'lang105',
    'Turkish': 'lang110',
    'Ukrainian': 'lang111',
    'Vietnamese': 'lang113'
}